// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_slice: dynamic(() => import("./AboutSlice")),
  hero_slice: dynamic(() => import("./HeroSlice")),
  projects_slice: dynamic(() => import("./ProjectsSlice")),
  quote_slice: dynamic(() => import("./QuoteSlice")),
  services_slice: dynamic(() => import("./ServicesSlice")),
  testimonials_slice: dynamic(() => import("./TestimonialsSlice")),
};
