// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_slice: dynamic(() => import("./AboutSlice")),
  content_slice: dynamic(() => import("./ContentSlice")),
  contact_slice: dynamic(() => import("./ContactSlice")),
  content_slice: dynamic(() => import("./ContentSlice")),
  hero_slice: dynamic(() => import("./HeroSlice")),
  map_slice: dynamic(() => import("./MapSlice")),
  projects_slice: dynamic(() => import("./ProjectsSlice")),
  quote_slice: dynamic(() => import("./QuoteSlice")),
  services_slice: dynamic(() => import("./ServicesSlice")),
  story_slice: dynamic(() => import("./StorySlice")),
  testimonials_slice: dynamic(() => import("./TestimonialsSlice")),
  video_slice: dynamic(() => import("./VideoSlice")),
};
